"""Specification for layers to be generated for the layer gallery."""

from xyzservices import TileProvider

from layer_gallery.models import (
    GallerySpecification,
    GeoJSONLayer,
    LayerEntry,
    ThumbnailConfig,
    XYZServicesRef,
)

_france_thumbnail = ThumbnailConfig(
    lat=47.040182144806664,
    lng=1.2963867187500002,
    zoom=5,
)
_sanfrancisco_thumbnail = ThumbnailConfig(lat=37.7749, lng=-122.4194, zoom=5)

gallery: GallerySpecification = {
    "OpenStreetMap": {
        "Mapnik": LayerEntry(
            name="OpenStreetMap.Mapnik",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["OpenStreetMap", "Mapnik"]),
            thumbnail=_france_thumbnail,
        ),
        "BZH": LayerEntry(
            name="OpenStreetMap.BZH",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["OpenStreetMap", "BZH"]),
            thumbnail=ThumbnailConfig(
                lat=47.76702233051035,
                lng=-3.4675598144531254,
                zoom=8,
            ),
        ),
        "CAT": LayerEntry(
            name="OpenStreetMap.CAT",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["OpenStreetMap", "CAT"]),
            thumbnail=_france_thumbnail,
        ),
        "CH": LayerEntry(
            name="OpenStreetMap.CH",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["OpenStreetMap", "CH"]),
            thumbnail=ThumbnailConfig(lat=46.8182, lng=8.2275, zoom=8),
        ),
        "DE": LayerEntry(
            name="OpenStreetMap.DE",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["OpenStreetMap", "DE"]),
            thumbnail=ThumbnailConfig(lat=51.1657, lng=10.4515, zoom=8),
        ),
        "France": LayerEntry(
            name="OpenStreetMap.France",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["OpenStreetMap", "France"]),
            thumbnail=_france_thumbnail,
        ),
        "HOT": LayerEntry(
            name="OpenStreetMap.HOT",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["OpenStreetMap", "HOT"]),
            thumbnail=_france_thumbnail,
        ),
    },
    # NOTE: `time=""` tells the generator to substitute yesterday's date at build time.
    "NASAGIBS": {
        "ModisTerraTrueColorCR": LayerEntry(
            name="NASAGIBS.ModisTerraTrueColorCR",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ModisTerraTrueColorCR",
                url="https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{max_zoom}/{z}/{y}/{x}.{format}",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=9,
                min_zoom=1,
                variant="MODIS_Terra_CorrectedReflectance_TrueColor",
                time="",
                tilematrixset="GoogleMapsCompatible_Level",
                format="jpg",
            ),
            thumbnail=_france_thumbnail,
        ),
        "ModisTerraBands367CR": LayerEntry(
            name="NASAGIBS.ModisTerraBands367CR",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ModisTerraBands367CR",
                url="https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{max_zoom}/{z}/{y}/{x}.{format}",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=9,
                min_zoom=1,
                variant="MODIS_Terra_CorrectedReflectance_Bands367",
                time="",
                tilematrixset="GoogleMapsCompatible_Level",
                format="jpg",
            ),
            thumbnail=_france_thumbnail,
        ),
        "ViirsEarthAtNight2012": LayerEntry(
            name="NASAGIBS.ViirsEarthAtNight2012",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ViirsEarthAtNight2012",
                url="https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{max_zoom}/{z}/{y}/{x}.{format}",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=8,
                min_zoom=1,
                variant="VIIRS_CityLights_2012",
                time="",
                tilematrixset="GoogleMapsCompatible_Level",
                format="jpg",
            ),
            thumbnail=_france_thumbnail,
        ),
        "ModisTerraLSTDay": LayerEntry(
            name="NASAGIBS.ModisTerraLSTDay",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ModisTerraLSTDay",
                url="https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{max_zoom}/{z}/{y}/{x}.{format}",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=7,
                min_zoom=1,
                variant="MODIS_Terra_Land_Surface_Temp_Day",
                time="",
                tilematrixset="GoogleMapsCompatible_Level",
                format="png",
            ),
            thumbnail=_france_thumbnail,
        ),
        "ModisTerraSnowCover": LayerEntry(
            name="NASAGIBS.ModisTerraSnowCover",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ModisTerraSnowCover",
                url="https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{max_zoom}/{z}/{y}/{x}.{format}",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=8,
                min_zoom=1,
                variant="MODIS_Terra_NDSI_Snow_Cover",
                time="",
                tilematrixset="GoogleMapsCompatible_Level",
                format="png",
            ),
            thumbnail=_france_thumbnail,
        ),
        "ModisTerraAOD": LayerEntry(
            name="NASAGIBS.ModisTerraAOD",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ModisTerraAOD",
                url="https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{max_zoom}/{z}/{y}/{x}.{format}",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=6,
                min_zoom=1,
                variant="MODIS_Terra_Aerosol",
                time="",
                tilematrixset="GoogleMapsCompatible_Level",
                format="png",
            ),
            thumbnail=_france_thumbnail,
        ),
        "ModisTerraChlorophyll": LayerEntry(
            name="NASAGIBS.ModisTerraChlorophyll",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ModisTerraChlorophyll",
                url="https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{max_zoom}/{z}/{y}/{x}.{format}",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=7,
                min_zoom=1,
                variant="MODIS_Terra_L2_Chlorophyll_A",
                time="",
                tilematrixset="GoogleMapsCompatible_Level",
                format="png",
            ),
            thumbnail=_france_thumbnail,
        ),
        "ModisTerraBands721CR": LayerEntry(
            name="NASAGIBS.ModisTerraBands721CR",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ModisTerraBands721CR",
                url="https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_Bands721/default/{time}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=9,
                time="",
            ),
            thumbnail=_france_thumbnail,
        ),
        "ModisAquaTrueColorCR": LayerEntry(
            name="NASAGIBS.ModisAquaTrueColorCR",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ModisAquaTrueColorCR",
                url="https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Aqua_CorrectedReflectance_TrueColor/default/{time}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=9,
                time="",
            ),
            thumbnail=_france_thumbnail,
        ),
        "ModisAquaBands721CR": LayerEntry(
            name="NASAGIBS.ModisAquaBands721CR",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ModisAquaBands721CR",
                url="https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Aqua_CorrectedReflectance_Bands721/default/{time}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=9,
                time="",
            ),
            thumbnail=_france_thumbnail,
        ),
        "ViirsTrueColorCR": LayerEntry(
            name="NASAGIBS.ViirsTrueColorCR",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ViirsTrueColorCR",
                url="https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/VIIRS_SNPP_CorrectedReflectance_TrueColor/default/{time}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=9,
                time="",
            ),
            thumbnail=_france_thumbnail,
        ),
        "ASTER_GDEM_Greyscale_Shaded_Relief": LayerEntry(
            name="NASAGIBS.ASTER_GDEM_Greyscale_Shaded_Relief",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NASAGIBS.ASTER_GDEM_Greyscale_Shaded_Relief",
                url="https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/ASTER_GDEM_Greyscale_Shaded_Relief/default/GoogleMapsCompatible_Level12/{z}/{y}/{x}.jpg",
                attribution="Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.",
                max_zoom=12,
            ),
            thumbnail=_france_thumbnail,
        ),
    },
    "WaymarkedTrails": {
        "hiking": LayerEntry(
            name="WaymarkedTrails.hiking",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["WaymarkedTrails", "hiking"]),
            thumbnail=_france_thumbnail,
        ),
        "cycling": LayerEntry(
            name="WaymarkedTrails.cycling",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["WaymarkedTrails", "cycling"]),
            thumbnail=_france_thumbnail,
        ),
        "mtb": LayerEntry(
            name="WaymarkedTrails.mtb",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["WaymarkedTrails", "mtb"]),
            thumbnail=_france_thumbnail,
        ),
        "slopes": LayerEntry(
            name="WaymarkedTrails.slopes",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["WaymarkedTrails", "slopes"]),
            thumbnail=_france_thumbnail,
        ),
        "riding": LayerEntry(
            name="WaymarkedTrails.riding",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["WaymarkedTrails", "riding"]),
            thumbnail=_france_thumbnail,
        ),
        "skating": LayerEntry(
            name="WaymarkedTrails.skating",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["WaymarkedTrails", "skating"]),
            thumbnail=_france_thumbnail,
        ),
    },
    "USGS": {
        "USTopo": LayerEntry(
            name="USGS.USTopo",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["USGS", "USTopo"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "USImagery": LayerEntry(
            name="USGS.USImagery",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["USGS", "USImagery"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "USImageryTopo": LayerEntry(
            name="USGS.USImageryTopo",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["USGS", "USImageryTopo"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
    },
    "Gaode": {
        "Normal": LayerEntry(
            name="Gaode.Normal",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="Gaode.Normal",
                url="http://webrd01.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=7&x={x}&y={y}&z={z}",
                attribution='&copy; <a href="http://www.gaode.com/">Gaode.com</a>',
                max_zoom=19,
            ),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "Satellite": LayerEntry(
            name="Gaode.Satellite",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="Gaode.Satellite",
                url="http://webst01.is.autonavi.com/appmaptile?style=6&x={x}&y={y}&z={z}",
                attribution='&copy; <a href="http://www.gaode.com/">Gaode.com</a>',
                max_zoom=19,
            ),
            thumbnail=_sanfrancisco_thumbnail,
        ),
    },
    "Strava": {
        "All": LayerEntry(
            name="Strava.All",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="Strava.All",
                url="https://heatmap-external-a.strava.com/tiles/all/hot/{z}/{x}/{y}.png",
                attribution='Map tiles by <a href="https://labs.strava.com/heatmap">Strava 2021</a>',
                max_zoom=15,
            ),
            thumbnail=_france_thumbnail,
        ),
        "Ride": LayerEntry(
            name="Strava.Ride",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="Strava.Ride",
                url="https://heatmap-external-a.strava.com/tiles/ride/hot/{z}/{x}/{y}.png",
                attribution='Map tiles by <a href="https://labs.strava.com/heatmap">Strava 2021</a>',
                max_zoom=15,
            ),
            thumbnail=_france_thumbnail,
        ),
        "Run": LayerEntry(
            name="Strava.Run",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="Strava.Run",
                url="https://heatmap-external-a.strava.com/tiles/run/bluered/{z}/{x}/{y}.png",
                attribution='Map tiles by <a href="https://labs.strava.com/heatmap">Strava 2021</a>',
                max_zoom=15,
            ),
            thumbnail=_france_thumbnail,
        ),
        "Water": LayerEntry(
            name="Strava.Water",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="Strava.Water",
                url="https://heatmap-external-a.strava.com/tiles/water/blue/{z}/{x}/{y}.png",
                attribution='Map tiles by <a href="https://labs.strava.com/heatmap">Strava 2021</a>',
                max_zoom=15,
            ),
            thumbnail=_france_thumbnail,
        ),
        "Winter": LayerEntry(
            name="Strava.Winter",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="Strava.Winter",
                url="https://heatmap-external-a.strava.com/tiles/winter/hot/{z}/{x}/{y}.png",
                attribution='Map tiles by <a href="https://labs.strava.com/heatmap">Strava 2021</a>',
                max_zoom=15,
            ),
            thumbnail=_france_thumbnail,
        ),
    },
    "Esri": {
        "WorldStreetMap": LayerEntry(
            name="Esri.WorldStreetMap",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["Esri", "WorldStreetMap"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "WorldTopoMap": LayerEntry(
            name="Esri.WorldTopoMap",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["Esri", "WorldTopoMap"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "WorldImagery": LayerEntry(
            name="Esri.WorldImagery",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["Esri", "WorldImagery"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "WorldTerrain": LayerEntry(
            name="Esri.WorldTerrain",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["Esri", "WorldTerrain"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "WorldShadedRelief": LayerEntry(
            name="Esri.WorldShadedRelief",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["Esri", "WorldShadedRelief"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "WorldPhysical": LayerEntry(
            name="Esri.WorldPhysical",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["Esri", "WorldPhysical"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "OceanBasemap": LayerEntry(
            name="Esri.OceanBasemap",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["Esri", "OceanBasemap"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "NatGeoWorldMap": LayerEntry(
            name="Esri.NatGeoWorldMap",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["Esri", "NatGeoWorldMap"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "WorldGrayCanvas": LayerEntry(
            name="Esri.WorldGrayCanvas",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["Esri", "WorldGrayCanvas"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        # Not (yet) in xyzservices  # noqa: ERA001
        "WorldDarkGrayCanvas": LayerEntry(
            name="Esri.WorldDarkGrayCanvas",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="Esri.WorldDarkGrayCanvas",
                url="https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}",
                variant="Canvas/World_Dark_Gray_Base",
                attribution="Tiles (C) Esri -- Esri, DeLorme, NAVTEQ",
                max_zoom=16,
            ),
            thumbnail=_sanfrancisco_thumbnail,
        ),
    },
    "MacroStrat": {
        "CartoRaster": LayerEntry(
            name="MacroStrat.CartoRaster",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="MacroStrat.CartoRaster",
                url="https://tiles.macrostrat.org/carto-slim/{z}/{x}/{y}.png",
                attribution="\u00a9 Geologic data \u00a9 <a href=https://macrostrat.org>Macrostrat raster layer</a> (CC\u2011BY 4.0)",
                max_zoom=18,
            ),
            thumbnail=_france_thumbnail,
        ),
        "CartoVector": LayerEntry(
            name="MacroStrat.CartoVector",
            layer_type="VectorTileLayer",
            source_type="VectorTileSource",
            data_source=TileProvider(
                name="MacroStrat.CartoVector",
                url="https://tiles.macrostrat.org/carto-slim/{z}/{x}/{y}.mvt",
                attribution="\u00a9 Geologic data \u00a9 <a href=https://macrostrat.org>Macrostrat vector layer</a> (CC\u2011BY 4.0)",
                max_zoom=18,
            ),
            layer_parameters={
                "opacity": 1,
                "color": {
                    "fill-color": ["coalesce", ["get", "color"], [0, 0, 0, 0]],
                    "circle-fill-color": ["coalesce", ["get", "color"], [0, 0, 0, 0]],
                    "stroke-color": ["coalesce", ["get", "color"], [0, 0, 0, 0]],
                    "circle-stroke-color": ["coalesce", ["get", "color"], [0, 0, 0, 0]],
                },
                "symbologyState": {
                    "renderType": "Canonical",
                    "value": "color",
                    "fallbackColor": [0, 0, 0, 0],
                    "strokeFollowsFill": True,
                },
            },
            thumbnail=_france_thumbnail,
        ),
    },
    # NOTE: GeoJSON entries have manually-created thumbnails.
    "NaturalEarth": {
        "Coastlines110m": LayerEntry(
            name="NaturalEarth.Coastlines110m",
            layer_type="VectorLayer",
            source_type="GeoJSONSource",
            data_source=GeoJSONLayer(
                path="https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_coastline.geojson",
                attribution="Natural Earth",
            ),
            layer_parameters={
                "opacity": 1,
                "color": {
                    "stroke-color": "#ffffff",
                    "stroke-width": 1.0,
                    "fill-color": "rgba(0,0,0,0)",
                },
                "symbologyState": {"renderType": "Single Symbol"},
            },
            thumbnail=_france_thumbnail,
            description="Natural Earth 110m coastlines — transparent vector overlay, no API key required",
        ),
        "Coastlines50m": LayerEntry(
            name="NaturalEarth.Coastlines50m",
            layer_type="VectorLayer",
            source_type="GeoJSONSource",
            data_source=GeoJSONLayer(
                path="https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_coastline.geojson",
                attribution="Natural Earth",
            ),
            layer_parameters={
                "opacity": 1,
                "color": {
                    "stroke-color": "#ffffff",
                    "stroke-width": 1.0,
                    "fill-color": "rgba(0,0,0,0)",
                },
                "symbologyState": {"renderType": "Single Symbol"},
            },
            thumbnail=_france_thumbnail,
            description="Natural Earth 50m coastlines — transparent vector overlay, no API key required",
        ),
        "Countries110m": LayerEntry(
            name="NaturalEarth.Countries110m",
            layer_type="VectorLayer",
            source_type="GeoJSONSource",
            data_source=GeoJSONLayer(
                path="https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson",
                attribution="Natural Earth",
            ),
            layer_parameters={
                "opacity": 1,
                "color": {
                    "stroke-color": "#ffffff",
                    "stroke-width": 1.0,
                    "fill-color": "rgba(0,0,0,0)",
                },
                "symbologyState": {"renderType": "Single Symbol"},
            },
            thumbnail=_france_thumbnail,
            description="Natural Earth 110m country boundaries — transparent vector overlay, no API key required",
        ),
        "Countries50m": LayerEntry(
            name="NaturalEarth.Countries50m",
            layer_type="VectorLayer",
            source_type="GeoJSONSource",
            data_source=GeoJSONLayer(
                path="https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson",
                attribution="Natural Earth",
            ),
            layer_parameters={
                "opacity": 1,
                "color": {
                    "stroke-color": "#ffffff",
                    "stroke-width": 1.0,
                    "fill-color": "rgba(0,0,0,0)",
                },
                "symbologyState": {"renderType": "Single Symbol"},
            },
            thumbnail=_france_thumbnail,
            description="Natural Earth 50m country boundaries — transparent vector overlay, no API key required",
        ),
        "Rivers110m": LayerEntry(
            name="NaturalEarth.Rivers110m",
            layer_type="VectorLayer",
            source_type="GeoJSONSource",
            data_source=GeoJSONLayer(
                path="https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_rivers_lake_centerlines.geojson",
                attribution="Natural Earth",
            ),
            layer_parameters={
                "opacity": 1,
                "color": {
                    "stroke-color": "#ffffff",
                    "stroke-width": 1.0,
                    "fill-color": "rgba(0,0,0,0)",
                },
                "symbologyState": {"renderType": "Single Symbol"},
            },
            thumbnail=_france_thumbnail,
            description="Natural Earth 110m rivers and lake centerlines — transparent vector overlay, no API key required",
        ),
        "Rivers50m": LayerEntry(
            name="NaturalEarth.Rivers50m",
            layer_type="VectorLayer",
            source_type="GeoJSONSource",
            data_source=GeoJSONLayer(
                path="https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_rivers_lake_centerlines.geojson",
                attribution="Natural Earth",
            ),
            layer_parameters={
                "opacity": 1,
                "color": {
                    "stroke-color": "#ffffff",
                    "stroke-width": 1.0,
                    "fill-color": "rgba(0,0,0,0)",
                },
                "symbologyState": {"renderType": "Single Symbol"},
            },
            thumbnail=_france_thumbnail,
            description="Natural Earth 50m rivers and lake centerlines — transparent vector overlay, no API key required",
        ),
    },
    "Other": {
        "OPNVKarte": LayerEntry(
            name="OPNVKarte",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["OPNVKarte"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "OpenTopoMap": LayerEntry(
            name="OpenTopoMap",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["OpenTopoMap"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "OpenRailwayMap": LayerEntry(
            name="OpenRailwayMap",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=XYZServicesRef(["OpenRailwayMap"]),
            thumbnail=_sanfrancisco_thumbnail,
        ),
        "WorldBoundariesAndPlaces": LayerEntry(
            name="WorldBoundariesAndPlaces",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NaturalEarth.WorldBoundariesAndPlaces",
                url="https://services.arcgisonline.com/arcgis/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}",
                attribution="\u00a9 Esri, HERE, Garmin, \u00a9 OpenStreetMap contributors",
                max_zoom=13,
            ),
            thumbnail=_france_thumbnail,
            description="\u00a9 Esri \u2014 Country boundaries and place labels as transparent overlay, no API key required",
        ),
        "WorldOceanReference": LayerEntry(
            name="WorldOceanReference",
            layer_type="RasterLayer",
            source_type="RasterSource",
            data_source=TileProvider(
                name="NaturalEarth.WorldOceanReference",
                url="https://services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Reference/MapServer/tile/{z}/{y}/{x}",
                attribution="\u00a9 Esri, Garmin, GEBCO, NOAA NGDC",
                max_zoom=13,
            ),
            thumbnail=_france_thumbnail,
            description="\u00a9 Esri \u2014 Coastlines and ocean reference labels as transparent overlay, no API key required",
        ),
    },
}
