# See https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
    nodejs: "20"
  jobs:
    # Install uv
    pre_create_environment:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH="$HOME/.local/bin:$PATH"
      - /bin/bash --login -c "uv --version"

    # Create and lock environments using uv
    create_environment:
      # Sync the environment for building the docs
      - /bin/bash --login -c "uv python install 3.12"
      - /bin/bash --login -c "uv sync --group docs"
      # Sync the build environment for JupyterGIS
      - /bin/bash --login -c "uv sync --group build"

    # Override the install step to do nothing - environments are already created
    install:
      - "echo 'Skipping! We already have the environments we need.'"

    # Before building the docs, build JupyterGIS in its isolated environment,
    # then install the wheels into the docs environment.
    pre_build:
      - /bin/bash --login -c "uv run jupytergis-build jlpm install"
      - /bin/bash --login -c "uv run jupytergis-build jlpm run dev"
      - /bin/bash --login -c "uv run jupytergis-build jupyter labextension list 2>&1 | grep -ie 'jupytergis-core.*OK'"
      - /bin/bash --login -c "uv run jupytergis-build jupyter labextension list 2>&1 | grep -ie 'jupytergis-lab.*OK'"
      - /bin/bash --login -c "uv run jupytergis-build jlpm run build:packages"

      - |-
        /bin/bash --login -c "uv run jupytergis-docs python -m pip install \
          $(ls ./python/jupytergis_core/dist/jupytergis*.whl) \
          $(ls ./python/jupytergis_lab/dist/jupytergis*.whl) \
          $(ls ./python/jupytergis_qgis/dist/jupytergis*.whl)"

    build:
      html:
        - |-
          /bin/bash --login -c "uv run jupytergis-docs python -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs \
          $READTHEDOCS_OUTPUT/html"
