# See https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python
    python: "mambaforge-latest"
    nodejs: "20"
  jobs:
    # We need new versions to support the 'emscripten' platform
    pre_create_environment:
      - conda install -n base -c conda-forge "conda>=24.11.2"
    # Before building the docs, build JupyterGIS in an isolated environment,
    # then install the wheels into the docs environment.
    pre_build:
      - mamba create -n jupytergis-build -c conda-forge yarn=3 hatch pip python=3.10
      - mamba run -n jupytergis-build pip install -r requirements-build.txt
      - mamba run -n jupytergis-build yarn install
      - mamba run -n jupytergis-build yarn dev
      - mamba run -n jupytergis-build jupyter labextension list 2>&1 | grep -ie "jupytergis-core.*OK"
      - mamba run -n jupytergis-build jupyter labextension list 2>&1 | grep -ie "jupytergis-lab.*OK"

      - mamba run -n jupytergis-build yarn build:packages

      # Install the wheels into the main docs environment, which is activated
      # automatically:
      - >-
        python -m pip install
        $(ls ./python/jupytergis_core/dist/jupytergis*.whl)
        $(ls ./python/jupytergis_lab/dist/jupytergis*.whl)
        $(ls ./python/jupytergis_qgis/dist/jupytergis*.whl)


sphinx:
  configuration: "docs/conf.py"
  # There doesn't seem to be a way to turn on nitpicky mode.
  # This is equivalent to `-W --keep-going`.
  # TODO: Enable after merging https://github.com/geojupyter/jupytergis/pull/273/
  # fail_on_warning: True

conda:
  environment: "docs/environment-docs.yml"
