// Re-exported from @jupytergis/schema — the canonical location for these types.
export type {
  RGBA,
  ClassificationMode,
  IPredicate,
  OutputType,
  RGBAChannel,
  UInt8Channel,
  UNormChannel,
  PosFloatChannel,
  OLStyleChannel,
  IColorRampScale,
  ICategoricalScale,
  IScalarScale,
  IKDEScale,
  IConstantRGBAScale,
  IConstantNumScale,
  IIdentityScale,
  IScale,
  IMapping,
  IEncodingRule,
  IGrammarSymbologyState,
} from '@jupytergis/schema';
