name: '🧪 Experience report'
description: 'Share your experience using JupyterGIS; anything goes.'
labels:
  - 'experience report'
body:
  - type: 'textarea'
    attributes:
      label: 'Description'
      description: |
        Please describe your experience clearly.
        We'd love to hear where you experienced friction, unintuitive behavior, or joy when using JupyterGIS.
    validations:
      required: true
