name: gis-nblink-environment
channels:
  - https://prefix.dev/emscripten-forge-4x
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-python
  - pydantic
  - pycrdt
  - markupsafe
  - pip:
      - jupytergis-lite==0.16.0a3
