import { ColorRampName, IColorRampDefinition } from '@/src/types';

export const COLOR_RAMP_DEFINITIONS = {
  'rainbow-soft': { type: 'Cyclic' },
  hsv: { type: 'Cyclic' },
  phase: { type: 'Cyclic' },
  jet: { type: 'Sequential' },
  hot: { type: 'Sequential' },
  cool: { type: 'Sequential' },
  spring: { type: 'Sequential' },
  summer: { type: 'Sequential' },
  autumn: { type: 'Sequential' },
  winter: { type: 'Sequential' },
  bone: { type: 'Sequential' },
  copper: { type: 'Sequential' },
  greys: { type: 'Sequential' },
  YiGnBu: { type: 'Sequential' },
  greens: { type: 'Sequential' },
  YiOrRd: { type: 'Sequential' },
  bluered: { type: 'Sequential' },
  RdBu: { type: 'Sequential' },
  rainbow: { type: 'Sequential' },
  portland: { type: 'Sequential' },
  blackbody: { type: 'Sequential' },
  earth: { type: 'Sequential' },
  electric: { type: 'Sequential' },
  viridis: { type: 'Sequential' },
  inferno: { type: 'Sequential' },
  magma: { type: 'Sequential' },
  plasma: { type: 'Sequential' },
  warm: { type: 'Sequential' },
  bathymetry: { type: 'Sequential' },
  cdom: { type: 'Sequential' },
  chlorophyll: { type: 'Sequential' },
  density: { type: 'Sequential' },
  'freesurface-blue': { type: 'Sequential' },
  'freesurface-red': { type: 'Sequential' },
  oxygen: { type: 'Sequential' },
  par: { type: 'Sequential' },
  salinity: { type: 'Sequential' },
  temperature: { type: 'Sequential' },
  turbidity: { type: 'Sequential' },
  'velocity-blue': { type: 'Sequential' },
  'velocity-green': { type: 'Sequential' },
  cubehelix: { type: 'Sequential' },
  ice: { type: 'Sequential' },
  oxy: { type: 'Sequential' },
  matter: { type: 'Sequential' },
  amp: { type: 'Sequential' },
  tempo: { type: 'Sequential' },
  rain: { type: 'Sequential' },
  topo: { type: 'Sequential' },
  picnic: { type: 'Divergent', criticalValue: 0.5 },
  balance: { type: 'Divergent', criticalValue: 0.5 },
  delta: { type: 'Divergent', criticalValue: 0.5 },
  curl: { type: 'Divergent', criticalValue: 0.5 },
  diff: { type: 'Divergent', criticalValue: 0.5 },
  tarn: { type: 'Divergent', criticalValue: 0.5 },
} as const satisfies { [key: string]: IColorRampDefinition };

export const COLOR_RAMP_DEFAULTS: Partial<Record<ColorRampName, number>> = {
  hsv: 11,
  picnic: 11,
  'rainbow-soft': 11,
  cubehelix: 16,
};
