import os
from enum import Enum

on_rtd = os.environ.get("READTHEDOCS", None) == "True"

html_theme = "pydata_sphinx_theme"
html_theme_options = {
    "github_url": "https://github.com/geojupyter/jupytergis",
    "navbar_align": "left",
    "header_links_before_dropdown": 6,
    "pygments_light_style": "tango",
    "pygments_dark_style": "monokai",
    "navbar_end": [
        "theme-switcher",
        "navbar-icon-links",
    ],
    "external_links": [
        {"name": "Try", "url": "lite/lab/index.html"},
    ],
}

# Hide left sidebar on single-page sections; keep it for Users and Contributors
html_sidebars = {
    "index": [],
    "getting_started/*": [],
    "changelog": [],
}

html_static_path = ["assets"]
html_css_files = [
    "css/custom.css",
]

extensions = [
    "jupyterlite_sphinx",
    "sphinx.ext.autodoc",
    "sphinx_autodoc_typehints",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinxcontrib.mermaid",
    "sphinxcontrib.bibtex",
    "sphinx_inline_tabs",
    "sphinx_exercise",
    "sphinx_togglebutton",
    "sphinx_copybutton",
    "myst_parser",
]

myst_enable_extensions = [
    "colon_fence",
]
myst_fence_as_directive = ["mermaid"]

master_doc = "index"
project = "JupyterGIS"
html_title = "JupyterGIS"
copyright = "2024, The JupyterGIS Development Team"
author = "The JupyterGIS Development Team"
language = "en"

bibtex_bibfiles = [
    "refs.bib",
]

jupyterlite_contents = [
    "../examples",
]
jupyterlite_ignore_contents = [
    r"\.\./examples/tiler-.*",
]
jupyterlite_dir = "."
jupyterlite_config = "jupyter_lite_config.json"
jupyterlite_silence = False

exclude_patterns = []
highlight_language = "python"
pygments_style = "sphinx"
todo_include_todos = False
htmlhelp_basename = "jupytergisdoc"

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "titiler": ("https://developmentseed.org/titiler/", None),
    "xarray": ("https://docs.xarray.dev/en/stable/", None),
    "pydantic": ("https://docs.pydantic.dev/latest/", None),
}

nitpick_ignore = [
    ("py:mod", "ypywidgets"),
    (
        "py:class",
        "titiler.core.algorithm.base.BaseAlgorithm",
    ),  # TiTiler's docs don't include this
]

jupyterlite_ignore_contents = [
    r".*\.qgz$",
    r"99-Explore_data_in_a_map\.ipynb$",
]


def _append_enum_values(_app, what, _name, obj, _options, lines):
    """Render enum docs as user-facing value lists."""
    if what != "class" or not isinstance(obj, type) or not issubclass(obj, Enum):
        return

    members = list(obj)
    if not members:
        return

    if lines and lines[-1].strip():
        lines.append("")
    lines.append("Allowed values:")
    for member in members:
        lines.append(f"- ``{member.value}``")


def _skip_enum_members(_app, _what, _name, obj, skip, _options):
    """Hide autogenerated enum member names in docs and keep value list only."""
    if isinstance(obj, Enum):
        return True
    return skip


def _enum_signature(_app, what, _name, obj, _options, signature, return_annotation):
    """Replace noisy Enum signatures with user-facing allowed values."""
    if what != "class" or not isinstance(obj, type) or not issubclass(obj, Enum):
        return signature, return_annotation

    members = list(obj)
    if not members:
        return signature, return_annotation

    values = ", ".join(repr(member.value) for member in members)
    return f"(allowed values: {values})", return_annotation


def setup(app):
    app.connect("autodoc-process-docstring", _append_enum_values)
    app.connect("autodoc-skip-member", _skip_enum_members)
    app.connect("autodoc-process-signature", _enum_signature)
