name: jupytergis-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python =3.13.*

  # Build docs & JupyterLite
  - jupyterlite-core
  - jupyterlite-xeus
  - micromamba
  - jupyterlite-sphinx
  - jupytext =1.19.0
  - sphinx
  - sphinx-inline-tabs
  - pydata-sphinx-theme
  - sphinx-autodoc-typehints
  - sphinx-exercise
  - sphinx-togglebutton
  - sphinx-copybutton
  - sphinxcontrib-mermaid
  - sphinxcontrib-bibtex
  - myst-parser
  - specta
  - pip
