name: Binder Badge
on:
  pull_request_target:
    types: [opened]

jobs:
  binder:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/binder-link@7bebe19dab1c58587eb734aca9184d8e59fdf911 # v1
        with:
          github_token: ${{ secrets.github_token }}
