name: Test-build without lockfile

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  test_build_without_lockfile:
    name: Test-build without lockfile
    runs-on: ubuntu-latest

    steps:
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@add3a49764cedee8ee24e82dfde87f5bc2914462 # v2
        with:
          environment-name: gis
          create-args: >-
            pip
            jupyterlab=4

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install build deps
        shell: bash -l {0}
        run: pip install -r requirements-build.txt

      - name: Build with a fresh yarn
        shell: bash -l {0}
        run: |
          rm yarn.lock
          jlpm
          jlpm run build:prod
