name: Test-build without lockfile

on:
  push:
    branches: main
  pull_request:
    branches: '*'

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: gis
          create-args: >-
            pip

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install build deps
        shell: bash -l {0}
        run: pip install --group build

      - name: Test build without lockfile
        shell: bash -l {0}
        run: |
          rm yarn.lock
          jlpm
          jlpm run build:prod
