name: Check links

on:
  push:
    branches: main
  pull_request:
    branches: '*'

permissions: {}

jobs:
  check_links:
    name: Check links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@b48fcdb87e70c45789abd80d4042b06641e47b46 # v1
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@b48fcdb87e70c45789abd80d4042b06641e47b46 # v1
        with:
          ignore_links: >-
            lite/
            https://www\.npmjs\.com.*
            ^/.*
            https://blog\.jupyter\.org/.*
            https://medium\.com/.*
