name: Check links

on:
  push:
    branches: main
  pull_request:
    branches: '*'

permissions: {}

jobs:
  check_links:
    name: Check links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@f5d710df1483f19b666dd96aeabbe949a53642c2 # v1
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@f5d710df1483f19b666dd96aeabbe949a53642c2 # v1
        with:
          ignore_links: >-
            lite/
            https://www\.npmjs\.com.*
            ^/.*
            https://blog\.jupyter\.org/.*
            https://medium\.com/.*
