name: Add preview link to PR

on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  comment-galata:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request'}}
    steps:
      - name: 'Comment galata link on workflow'
        uses: trungleduc/appsharingspace-pr-comment/.github/actions/pr-comment@v2
        with:
          comment_prefix: '**Integration tests report:**'
          artifact_name: galata-apss
          github_token: ${{ secrets.github_token }}
          index_path: playwright-report/index.html
