name: Lint

on:
  push:
    branches: main
  pull_request:
    branches: '*'

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          set -e

          yarn install
          yarn info

      # Unfortunately, we need to build to properly lint. If we don't build,
      # the types for cross-package dependencies won't be available and we'll
      # see false positives and negatives in our lint jobs.
      - name: Build
        run: |
          # Avoid installing jupyterlab to run the build
          # This is more complicated than desired because a simple bash alias
          # or function won't get picked up by yarn when running the "build"
          # script in package.json :(
          mkdir -p $HOME/.local/bin
          cat << 'EOF' > $HOME/.local/bin/jlpm
          #!/bin/bash
          exec yarn "$@"
          EOF
          chmod +x $HOME/.local/bin/jlpm
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          yarn run build

      - name: Lint
        id: eslint
        continue-on-error: true
        run: yarn run eslint:check

      - name: Check formatting
        id: prettier
        continue-on-error: true
        shell: bash -l {0}
        run: |
          yarn run prettier:check
          rc=$?

          if [ $rc -ne 0 ]; then
            # Show what was changed -- useful if CI is reporting an error and
            # local prettier run is not (╯°□°)╯︵ ┻━┻
            yarn run prettier
            git diff
            git restore .
          fi

          exit $rc

      - name: Report
        env:
          ESLINT_OUTCOME: ${{ steps.eslint.outcome }}
          PRETTIER_OUTCOME: ${{ steps.prettier.outcome }}
        run: |
          failed=0

          if [ "${ESLINT_OUTCOME}" == "success" ]; then
            echo "🎉 ESLint check passed"
          else
            echo "❌ ESLint check failed"
            failed=1
          fi

          if [ "${PRETTIER_OUTCOME}" == "success" ]; then
            echo "🎉 Prettier format check passed"
          else
            echo "❌ Prettier format check failed"
            failed=1
          fi

          exit $failed
