name: Lint JavaScript

on:
  push:
    branches: main
  pull_request:
    branches: '*'

permissions: {}

jobs:
  lint-js:
    name: eslint & prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          cache-environment: true
          environment-name: gis
          create-args: >-
            pip
            qgis

      - name: Setup pip cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            pip-${{ matrix.python-version }}-
            pip-

      - name: Install Python build deps
        shell: bash -l {0}
        run: pip install --group build

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        shell: bash -l {0}
        run: |
          set -e
          CACHE_DIR="$(jlpm config get cacheFolder)"
          echo "dir=${CACHE_DIR}" >> $GITHUB_OUTPUT

      - name: Setup yarn cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install JS build deps
        shell: bash -l {0}
        run: |
          set -e

          jlpm install
          jlpm info

      # Unfortunately, we need to build to properly lint. If we don't build,
      # the types for cross-package dependencies won't be available and we'll
      # see false positives and negatives in our lint jobs.
      - name: Build
        shell: bash -l {0}
        run: jlpm run build

      - name: Lint
        id: eslint
        continue-on-error: true
        shell: bash -l {0}
        run: jlpm run eslint:check

      - name: Check formatting
        id: prettier
        continue-on-error: true
        shell: bash -l {0}
        run: |
          jlpm run prettier:check
          rc=$?

          if [ $rc -ne 0 ]; then
            # Show what was changed -- useful if CI is reporting an error and
            # local prettier run is not (╯°□°)╯︵ ┻━┻
            jlpm run prettier
            git diff
            git restore .
          fi

          exit $rc

      - name: Report
        env:
          ESLINT_OUTCOME: ${{ steps.eslint.outcome }}
          PRETTIER_OUTCOME: ${{ steps.prettier.outcome }}
        run: |
          failed=0

          if [ "${ESLINT_OUTCOME}" == "success" ]; then
            echo "🎉 ESLint check passed"
          else
            echo "❌ ESLint check failed"
            failed=1
          fi

          if [ "${PRETTIER_OUTCOME}" == "success" ]; then
            echo "🎉 Prettier format check passed"
          else
            echo "❌ Prettier format check failed"
            failed=1
          fi

          exit $failed
