name: Unit test Python

on:
  push:
    branches: main
  pull_request:
    branches: '*'
    paths:
      - 'python/**'
      - 'scripts/**'
      - 'pyproject.toml'
      - '.github/workflows/unit-test-python.yml'

permissions: {}

jobs:
  unit-test-python:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          cache: true

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
        with:
          environment-name: gis
          create-args: >-
            python=${{ matrix.python-version }}
            qgis

      - name: Install
        shell: bash -l {0}
        run: python scripts/dev-install.py

      - name: Install test packages
        shell: bash -l {0}
        run: pip install --group test

      - name: Run QGIS tests
        shell: bash -l {0}
        run: pytest --color=yes -v python/jupytergis_qgis/jupytergis_qgis/tests

      - name: Run Python API tests
        shell: bash -l {0}
        run: pytest --color=yes -v python/jupytergis_lab/

      - name: Run layer gallery generator tests
        working-directory: ./scripts/layer_gallery
        shell: bash -l {0}
        run: uv run pytest --color=yes -v
