name: Unit test Python

on:
  push:
    branches: main
  pull_request:
    branches: '*'

permissions: {}

jobs:
  unit-test-python:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.14']

    steps:
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: gis
          create-args: >-
            python=${{ matrix.python-version }}
            qgis

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install
        shell: bash -l {0}
        run: python scripts/dev-install.py

      - name: Install test packages
        shell: bash -l {0}
        run: pip install --group test

      - name: Run QGIS tests
        shell: bash -l {0}
        run: pytest --color=yes -v python/jupytergis_qgis/jupytergis_qgis/tests

      - name: Run Python API tests
        shell: bash -l {0}
        run: pytest --color=yes -v python/jupytergis_lab/

      - name: Run layer gallery generator tests
        working-directory: ./scripts/layer_gallery
        shell: bash -l {0}
        run: uv run pytest --color=yes -v
