name: Unit test Python

on:
  push:
    branches: main
  pull_request:
    branches: '*'

permissions: {}

jobs:
  unit-test-python:
    name: Run Python unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.12']

    steps:
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@add3a49764cedee8ee24e82dfde87f5bc2914462 # v2
        with:
          environment-name: gis
          create-args: >-
            python=${{ matrix.python-version }}
            jupyterlab=4
            qgis

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install
        shell: bash -l {0}
        run: python scripts/dev-install.py

      - name: Install test packages
        shell: bash -l {0}
        run: pip install pytest dirty-equals

      - name: Run tests
        shell: bash -l {0}
        run: pytest --color=yes -v python/jupytergis_qgis/jupytergis_qgis/tests

      - name: Run Python API tests
        shell: bash -l {0}
        run: pytest --color=yes -v python/jupytergis_lab/
