name: Unit test JavaScript

on:
  push:
    branches: main
  pull_request:
    branches: '*'

permissions: {}

jobs:
  unit-test-js:
    name: jest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          cache-environment: true
          environment-name: gis
          create-args: >-
            pip

      - name: Install Python build deps
        shell: bash -l {0}
        run: pip install --group build

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        shell: bash -l {0}
        run: |
          set -e
          CACHE_DIR="$(jlpm config get cacheFolder)"
          echo "dir=${CACHE_DIR}" >> $GITHUB_OUTPUT

      - name: Setup yarn cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install JS dependencies
        shell: bash -l {0}
        run: jlpm install

      - name: Build
        shell: bash -l {0}
        run: jlpm run build

      - name: Run unit tests
        shell: bash -l {0}
        run: jlpm run test
