name: Unit test JavaScript

on:
  push:
    branches: main
  pull_request:
    branches: '*'

permissions: {}

jobs:
  unit-test-js:
    name: Run JavaScript unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@add3a49764cedee8ee24e82dfde87f5bc2914462 # v2
        with:
          cache-environment: true
          environment-name: gis
          create-args: >-
            pip

      - name: Install Python build deps
        shell: bash -l {0}
        run: pip install --group build

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        shell: bash -l {0}
        run: |
          set -e
          CACHE_DIR="$(jlpm config get cacheFolder)"
          echo "dir=${CACHE_DIR}" >> $GITHUB_OUTPUT

      - name: Setup yarn cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install JS dependencies
        shell: bash -l {0}
        run: jlpm install

      - name: Run unit tests
        shell: bash -l {0}
        working-directory: packages/base
        run: jlpm test
