name: Update Lite Galata References

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash -l {0}

jobs:
  update-lite-snapshots:
    runs-on: ubuntu-latest

    # Only run on issue comments
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'please update snapshots')

    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/update-snapshots-checkout@b48fcdb87e70c45789abd80d4042b06641e47b46
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true

      - name: Download extension package
        uses: dawidd6/action-download-artifact@b6e2e70617bc3265edd6dab6c906732b2f1ae151  # v21
        with:
          pr: ${{github.event.issue.number}}
          workflow: 'build.yml'
          workflow_conclusion: ''
          name: lite-artifacts
          path: dist
          allow_forks: true

      - name: Install dependencies
        shell: bash -l {0}
        working-directory: ui-tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
            pip install jupyterlab
            pnpm install --frozen-lockfile
            pnpm exec playwright install chromium

      - uses: jupyterlab/maintainer-tools/.github/actions/update-snapshots@b48fcdb87e70c45789abd80d4042b06641e47b46
        with:
          npm_client: pnpm
          browser: chromium
          github_token: ${{ secrets.GITHUB_TOKEN }}
          start_server_script: 'null'
          test_folder: ui-tests
          update_script: test:updatelite
